# Generated by Django 4.2.6 on 2023-12-01 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurantName', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('style', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('ratingID', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('comment', models.TextField()),
                ('restaurantName', models.ForeignKey(db_column='restaurantName', on_delete=django.db.models.deletion.CASCADE, to='restaurant_search.restaurant')),
            ],
            options={
                'db_table': 'Rating',
            },
        ),
    ]
