# Generated by Django 4.2.7 on 2023-11-26 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurantName', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('style', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('ratingID', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('comment', models.TextField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_search.restaurant')),
            ],
        ),
    ]
