# Generated by Django 4.2.8 on 2023-12-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
